# .github/workflows/update.yml
name: Update Awesome Repos

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'    # ← upgrade here :contentReference[oaicite:8]{index=8}

      - name: Install Dependencies
        run: npm install

      - name: Generate Repo Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/generate.js

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add by-owner/*.md
          git commit -m "chore: update starred repos" || echo "No changes"
          git push
